### ISSUE TITLE
Link to examples is broken

### ISSUE THREAD

**Issue by MartinSStewart** [opvasger/amr#2]
The link [here](https://package.elm-lang.org/packages/opvasger/amr/3.1.0/AMR#Config) that points to usage examples is broken. When I click on it I get a 404 on Github.

<img width="586" alt="Screen Shot 2019-09-27 at 9 17 23 AM" src="https://user-images.githubusercontent.com/5068391/65750028-b3daea80-e107-11e9-8674-193c9c658e58.png">

**Comment by opvasger** [comment]
The typo is fixed now - https://package.elm-lang.org/packages/opvasger/amr/3.1.1/AMR

Thanks for the report! :sunny:
